version: '3'

networks:
  laravel-sandi:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sandi
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel-sandi

  mysql:
    image: mysql:5.7.29
    container_name: mysql-sandi
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel-sandi

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-sandi
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel-sandi

  composer:
    image: composer:latest
    container_name: composer-sandi
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel-sandi

  npm:
    image: node:13.7
    container_name: npm-sandi
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

#  redis:
#    image: redis:4.0-alpine
#    container_name: redis-sandi
#    command: redis-server --appendonly yes
#    ports:
#      - "6379:6379"
#    networks:
#      - laravel-sandi
#
#  elastic:
#     image: elasticsearch:5.5-alpine
#     container_name: elastic-sandi
#     ports:
#       - "9200:9200"
#     networks:
#       - laravel-sandi

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan-sandi
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    networks:
      - laravel-sandi
